title: My Novel
description: A collection of chapters for my novel.
baseurl: "/novel/jekyll-novel-site" # Update this if your site is in a subdirectory
url: "https://seaboiii.github.io"
theme: minima
markdown: kramdown
permalink: pretty
exclude: ["_site", "README.md"]
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap