title: My Novel
description: A collection of chapters for my novel.
baseurl: ""
url: "https://yourusername.github.io/jekyll-novel-site"
theme: minima
markdown: kramdown
permalink: pretty
exclude: ["_site", "README.md"]
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap